name: desafio-brev-ly-prod

services:
  app-prod:
    container_name: brev-ly-api-prod
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    environment:
      - PORT=$PORT
      - NODE_ENV=production
      - POSTGRESQL_USERNAME=$POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRESQL_DATABASE=$POSTGRESQL_DATABASE
      - POSTGRESQL_PORT=$POSTGRESQL_PORT
      - DATABASE_URL=postgresql://$POSTGRESQL_USERNAME:$POSTGRESQL_PASSWORD@db:5432/$POSTGRESQL_DATABASE
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - app-network
