name: desafio-brev-ly-dev

services:
  app-dev:
    container_name: brev-ly-api-dev
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://$POSTGRESQL_USERNAME:$POSTGRESQL_PASSWORD@db:5432/$POSTGRESQL_DATABASE
    networks:
      - app-network
    command: ["sh", "-c", "pnpm db:migrate && pnpm start"]
